"""Markdown writer for llms.txt — newline-joined, UTF-8.

Header layout:
    intro line
    sitemap link
    # title
    > meta description
    ## Locales         (only when >1 locale is detected or root+1 locale)
    - Code (Language, Country) — root_url — N URLs
    ## <bucket>
    - ...
"""
from __future__ import annotations

import unicodedata
from datetime import datetime, timezone

from .locales import LocaleInfo

_REPL = {"ä": "ae", "ö": "oe", "ü": "ue", "Ä": "Ae", "Ö": "Oe", "Ü": "Ue", "ß": "ss"}


def de_ascii(txt: str) -> str:
    if not txt:
        return ""
    txt = "".join(_REPL.get(c, c) for c in txt)
    return unicodedata.normalize("NFKD", txt).encode("ascii", "ignore").decode("ascii")


def _slug_to_anchor(url: str) -> str:
    return url.rstrip("/").split("/")[-1].replace("-", " ").replace("_", " ").strip() or url


def render(
    *,
    df,
    sitemap_url: str,
    platform_name: str,
    bucket_order: list[str],
    bucket_translation: dict[str, str],
    title: str | None,
    meta_desc: str | None,
    include_locales: list[str] | None,
    ascii_only: bool,
    meta_map: dict[str, tuple[str, str]] | None,
    version: str,
    locales: list[LocaleInfo] | None = None,
) -> str:
    def fmt(s: str) -> str:
        return de_ascii(s) if ascii_only else s

    lines: list[str] = [
        f"Generated by Antonio Blago LLM txt Generator v{version} on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%SZ')}, "
        "this is an llms.txt file meant for consumption by LLMs.",
        "",
        f"This is the [sitemap]({sitemap_url}) of this website.",
        "",
    ]
    if title:
        lines += [f"# {fmt(title)}", ""]
    if meta_desc:
        lines += [f"> {fmt(meta_desc)}", ""]

    if locales and len(locales) > 1:
        lines.append("## Locales")
        for li in locales:
            human = fmt(li.human_name)
            lines.append(
                f"- **{li.display_code}** — {human} — [{li.root_url}]({li.root_url}) — {li.n_urls} URLs"
            )
        lines.append("")

    if include_locales:
        scope = ", ".join(include_locales)
        lines += [f"_Scope of URLs below:_ `{scope}`", ""]
    elif platform_name == "shopify":
        lines += ["_Scope of URLs below:_ `root` (default; use --locales all to include every locale)", ""]

    meta_map = meta_map or {}
    for internal in bucket_order:
        localized = bucket_translation.get(internal, internal)
        sub = df[df["bucket"] == internal]
        if sub.empty:
            continue
        lines.append(f"## {localized}")
        for url in sorted(sub["loc"]):
            pt, pd_ = meta_map.get(url, ("", ""))
            anchor = fmt(pt) if pt else fmt(_slug_to_anchor(url))
            line = f"- [{anchor}]({url})"
            if pd_:
                line += f" — {fmt(pd_)}"
            lines.append(line)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
